shared_preload_libraries = 'pg_stat_monitor'

pg_stat_monitor.pgsm_collect_per_query_statistics = 'false'

pg_stat_monitor.pgsm_log_min_duration = 0

pg_stat_monitor.pgsm_log_parameter_max_length = 0

pg_stat_monitor.pgsm_per_query_storage_capacity = 10

pg_stat_monitor.pgsm_worker_timeout = 100000

pg_stat_monitor.pgsm_spill_coefficient = 70

pg_stat_monitor.pgsm_per_query_dsa_size = 2
